### ISSUE TITLE
Tech stack ..?

### ISSUE THREAD

**Issue by ilham336** [ilhammmaulana/portofolio_2019#1]
what technology are you using?

**Comment by ilhammmaulana** [comment]
> what technology are you using?

Im using Bootstrap CSS JS its web static

**Comment by ilham336** [comment]
How to use Bootstarp using cdn

**Comment by ilhammmaulana** [comment]
> How to use Bootstarp using cdn
`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
` like this
